client_id = "0e94b8983e671068b33cdbd17dc54dc5"
name = "SQRATCH"
handle = "sqratch"
application_url = "https://sqratch.com/shopify"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://sqratch.com/api/shopify/oauth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://sqratch.com/api/shopify/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://sqratch.com/api/shopify/webhooks/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://sqratch.com/api/shopify/webhooks/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://sqratch.com/api/shopify/webhooks/shop/redact"
