client_id = "0e94b8983e671068b33cdbd17dc54dc5"
name = "sqratch-custom-app-test"
handle = "sqratch-custom-app-test"
application_url = "https://spyglass-excluding-silliness.ngrok-free.dev/shopify"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/orders/updated"
  topics = [ "orders/updated" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/refunds/create"
  topics = [ "refunds/create" ]

  [[webhooks.subscriptions]]
  uri = "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/webhooks/order_transactions/create"
  topics = [ "order_transactions/create" ]

[access_scopes]
scopes = "read_products,read_orders,read_themes,read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://spyglass-excluding-silliness.ngrok-free.dev/api/shopify/oauth/callback" ]
