/**
 * src/lib/commerce/types.ts
 *
 * Provider-neutral types shared by every commerce adapter. Nothing in this
 * file may reference a concrete provider's naming (no "shopify" / "gid://"
 * anywhere in a type name or field name) — the only external import allowed
 * is the `CommerceProvider` / `CommerceConnectionStatus` enums generated by
 * Prisma, which are themselves provider-neutral (Commerce7 is a value of
 * `CommerceProvider`, not a separate type).
 */

import type {
  CommerceConnectionStatus,
  CommerceProvider,
} from "@prisma/client";

/**
 * What a given adapter can actually do. Kept deliberately narrow — only the
 * capabilities the product surface exercises today. Do not add speculative
 * capabilities (orders, attribution, commissions, etc.) until a caller
 * actually needs them.
 */
export type CommerceCapabilities = {
  products: {
    sync: boolean;
    publicDestinations: boolean;
  };
  rewards: {
    create: boolean;
    lookup: boolean;
    usageLookup: boolean;
    revoke: boolean;
    fixedAmount: boolean;
    percentage: boolean;
    minimumSubtotal: boolean;
    productSpecific: boolean;
    singleUse: boolean;
  };
};

/** Provider-neutral state of storefront conversion tracking readiness. */
export type CommerceThemeTrackingState =
  "PERMISSION_REQUIRED" | "NOT_CONFIGURED" | "DISABLED" | "ENABLED" | "UNKNOWN";

export type CommerceThemeTrackingReadiness = {
  provider: CommerceProvider;
  state: CommerceThemeTrackingState;
};

/**
 * The neutral view of a commerce connection handed to business code.
 *
 * It never contains a credential field. A provider adapter owns its
 * credential policy: Shopify resolves a connection-bound
 * `CommerceConnectionSecret`; a future Commerce7 adapter will use the
 * backend app credential with this exact tenant connection identity.
 */
export type CommerceConnectionSummary = {
  id: string;
  brandId: string;
  provider: CommerceProvider;
  status: CommerceConnectionStatus;
  displayName: string;
  externalAccountId: string;
  storefrontUrl: string | null;
  isPrimary: boolean;
  grantedScopes: string[];
  installedAt: Date | null;
  uninstalledAt: Date | null;
  lastProductSyncAt: Date | null;
  /**
   * The canonical currency representation from
   * `CommerceConnection.providerMetadata.currencyCode`. Runtime consumers
   * read it only from this neutral connection summary.
   */
  currencyCode: string | null;
};

/**
 * Discriminated result union for connection lookups. Discriminated on the
 * literal `ok` field so callers get exhaustive narrowing without needing a
 * separate discriminant property.
 */
export type CommerceConnectionResult =
  | { ok: true; connection: CommerceConnectionSummary }
  | { ok: false; reason: "NOT_FOUND" | "NOT_CONNECTED" };

/**
 * A provider-neutral min/max price range. Mirrors
 * `NormalizedShopifyProduct.priceRange`'s exact shape
 * (`src/lib/shopify-products.ts`) — both bounds are `null` when a product has
 * no priced variants, and `min === max` for a single-price product.
 */
export type CommerceProductPriceRange = {
  min: number | null;
  max: number | null;
};

/**
 * Neutral product shape covering everything the storefront/reward UI reads
 * today. `externalId` replaces provider-specific ids (e.g. Shopify's
 * `shopifyProductGid`) at the neutral boundary — it is ALSO the source for
 * any provider-specific "id" a caller used to read separately: inspecting
 * `src/lib/shopify-products.ts`'s `normalizeProduct` shows Shopify's own
 * `NormalizedShopifyProduct.id` and `.shopifyProductGid` are always the exact
 * same value (`String(product.id)`, assigned to both fields) — there is no
 * second identifier to preserve, so no redundant neutral field is added here.
 * `externalVariantIds` replaces provider-specific variant ids (e.g.
 * Shopify's numeric variant ids, stringified).
 */
/**
 * Raw provider decimal price strings, mirroring
 * `NormalizedShopifyProduct.priceRangeRaw` (`src/lib/shopify-products.ts`) —
 * kept alongside the existing float `priceRange` so a persistence layer can
 * convert to exact integer minor units (via `src/lib/commerce/money.ts`)
 * instead of re-deriving from the already-lossy float value.
 */
export type CommerceProductPriceRangeRaw = {
  min: string | null;
  max: string | null;
};

export type CommerceProduct = {
  externalId: string;
  title: string;
  handle: string | null;
  productUrl: string;
  imageUrl: string | null;
  images: string[];
  priceText: string | null;
  currency: string;
  priceRange: CommerceProductPriceRange;
  externalVariantIds: string[];
  /**
   * Optional additive fields (Phase 3 data acquisition). All are `undefined`
   * unless the underlying provider adapter populates them — existing
   * callers that don't read them are completely unaffected.
   */
  /** Plain-text product description, if the provider exposes one. */
  descriptionText?: string | null;
  /** Product-level SKU (provider-specific derivation; see the Shopify adapter for how it's chosen). */
  sku?: string | null;
  /** Provider-reported lifecycle status (e.g. "ACTIVE" | "DRAFT" | "ARCHIVED"), passed through verbatim. */
  status?: string | null;
  /** When the provider reports the product was created. */
  providerCreatedAt?: Date | null;
  /** When the provider reports the product was last updated. */
  providerUpdatedAt?: Date | null;
  /** Raw decimal price strings — see `CommerceProductPriceRangeRaw`. */
  priceRangeRaw?: CommerceProductPriceRangeRaw;
  /**
   * TRUE only when the provider confirmed the product is published/usable on
   * its merchant storefront. It is never inferred from a URL, product status,
   * handle, inventory, or SQRATCH curation. Deliberately separate from
   * lifecycle availability; a public clickable destination requires both.
   * Undefined means the adapter did not provide complete evidence, which
   * persistence treats as fail-closed false.
   */
  hasProviderStorefrontPublication?: boolean;
  /**
   * TRUE only when `productUrl` itself was returned by the provider. This is
   * navigation provenance, not publication authorization: a passworded dev
   * store can have a published product but require the canonical fallback URL.
   * Sync persists only this boolean (never the raw provider payload) so the
   * click redirect can safely allow a Shopify custom-domain URL while keeping
   * synthesized fallback URLs pinned to the connection's shop domain.
   */
  hasProviderSuppliedStorefrontUrl?: boolean;
};

/**
 * Result of one adapter product fetch. The provider-neutral sync service may
 * subsequently reconcile these normalized products into the persisted catalog.
 *
 * `hasNextPage` / `limit` mirror `fetchNormalizedShopifyProducts`'s own
 * pagination signal (`src/lib/shopify-products.ts`) so a route's `meta`
 * response field can be reproduced without reaching past this neutral type
 * back into a provider-specific result shape.
 */
export type ProductSyncResult = {
  connectionId: string;
  provider: CommerceProvider;
  products: CommerceProduct[];
  productCount: number;
  syncedAt: Date;
  hasNextPage: boolean;
  limit: number;
};

/**
 * Provider-neutral request for one catalog page. `cursor` is opaque: callers
 * must only return a value previously supplied by the same adapter, never
 * inspect or construct it from provider-specific page-info data.
 */
export type ProductSyncPageRequest = {
  cursor?: string | null;
  limit?: number;
  /** Cancels an in-flight provider request when the logical sync expires. */
  signal?: AbortSignal;
  /**
   * Opaque provider-owned context prepared once for the logical catalog sync.
   * Business code must never inspect or construct it. It exists so a provider
   * can safely gather catalog-wide facts (such as storefront publication)
   * exactly once instead of re-fetching them for every product page.
   */
  syncContext?: unknown;
};

/**
 * Bounds and cancellation shared with an optional provider preparation step.
 * The returned context remains opaque to the neutral sync service.
 */
export type ProductSyncPreparationRequest = {
  limit?: number;
  maxPages?: number;
  maxProducts?: number;
  signal?: AbortSignal;
};

/**
 * One provider-neutral catalog page. A complete page MUST have
 * `nextCursor: null`; an incomplete page MUST provide a non-empty opaque
 * cursor. This deliberately exposes no provider GraphQL page-info shape.
 */
export type ProductSyncPageResult = {
  products: CommerceProduct[];
  nextCursor: string | null;
  isComplete: boolean;
  fetchedAt: Date;
  limit: number;
};

/**
 * Neutral input for creating a provider discount code. Mirrors the fields
 * `createShopifyRewardDiscountCode` accepts today, generalized so a future
 * provider (Commerce7, etc.) could implement the same shape.
 */
export type CreateDiscountInput = {
  code: string;
  title: string;
  issuedAt: Date;
  validDays: number;
  discountType: "FIXED_AMOUNT" | "PERCENTAGE";
  discountAmountCents: number | null;
  discountPercentageBasisPoints: number | null;
  appliesTo: "ALL_PRODUCTS" | "SPECIFIC_PRODUCTS";
  externalProductIds?: string[];
  minimumSubtotalCents?: number | null;
};

/**
 * Neutral discount result. Field selection matches exactly what
 * `src/app/api/rewards/shopify/redeem/route.ts` persists today
 * (`shopifyDiscountNodeId`, `code`, `expiresAt` on `ShopifyRewardRedemption`)
 * — no additional fields are included since nothing currently consumes
 * them.
 */
export type ProviderDiscount = {
  externalDiscountId: string;
  code: string;
  expiresAt: Date | null;
};

/** Opaque provider identifiers in, normalized discount facts out. */
export type GetDiscountInput = {
  externalDiscountId?: string;
  code?: string;
};

export type ProviderDiscountLookup =
  | {
      exists: true;
      externalDiscountId: string;
      externalStatus: string | null;
      usageCount: number;
      expiresAt: Date | null;
    }
  | { exists: false };
