/**
 * src/lib/commerce/types.ts
 *
 * Provider-neutral types shared by every commerce adapter. Nothing in this
 * file may reference a concrete provider's naming (no "shopify" / "gid://"
 * anywhere in a type name or field name) — the only external import allowed
 * is the `CommerceProvider` / `CommerceConnectionStatus` enums generated by
 * Prisma, which are themselves provider-neutral (Commerce7 is a value of
 * `CommerceProvider`, not a separate type).
 */

import type { CommerceConnectionStatus, CommerceProvider } from "@prisma/client";

/**
 * What a given adapter can actually do. Kept deliberately narrow — only the
 * capabilities the product surface exercises today. Do not add speculative
 * capabilities (orders, attribution, commissions, etc.) until a caller
 * actually needs them.
 */
export type CommerceCapabilities = {
  canSyncProducts: boolean;
  canCreateDiscount: boolean;
  canRevokeDiscount: boolean;
  canVerifyWebhooks: boolean;
};

/** Provider-neutral state of storefront conversion tracking readiness. */
export type CommerceThemeTrackingState =
  | "PERMISSION_REQUIRED"
  | "NOT_CONFIGURED"
  | "DISABLED"
  | "ENABLED"
  | "UNKNOWN";

export type CommerceThemeTrackingReadiness = {
  provider: CommerceProvider;
  state: CommerceThemeTrackingState;
};

/**
 * The neutral view of a commerce connection handed to business code.
 *
 * `id` is `null` and `isLegacyFallback` is `true` when this summary was
 * derived from legacy `Brand.shopify*` columns rather than an actual
 * `CommerceConnection` row (pre-migration brands). It never contains any
 * credential field — secrets live only in `CommerceConnectionSecret` and
 * are never surfaced through this type.
 */
export type CommerceConnectionSummary = {
  id: string | null;
  brandId: string;
  provider: CommerceProvider;
  status: CommerceConnectionStatus;
  displayName: string;
  externalAccountId: string;
  storefrontUrl: string | null;
  isPrimary: boolean;
  grantedScopes: string[];
  installedAt: Date | null;
  uninstalledAt: Date | null;
  lastProductSyncAt: Date | null;
  isLegacyFallback: boolean;
  /**
   * PHASE 14B.4B — the SINGLE canonical currency representation. For a real
   * `CommerceConnection` row this is `providerMetadata.currencyCode`
   * (populated on every install/sync — see `connection-sync.ts`'s
   * `buildShopifyConnectionSyncInput(FromInstall)`); for a legacy-derived
   * summary it is `Brand.shopifyCurrencyCode`, since that IS the only value
   * that ever existed for a pre-cutover brand. There is deliberately no
   * second currency field anywhere in this codebase — every runtime
   * consumer must read it from here, not from `Brand.shopifyCurrencyCode`
   * directly.
   */
  currencyCode: string | null;
};

/**
 * Discriminated result union for connection lookups. Discriminated on the
 * literal `ok` field so callers get exhaustive narrowing without needing a
 * separate discriminant property.
 */
export type CommerceConnectionResult =
  | { ok: true; connection: CommerceConnectionSummary }
  | { ok: false; reason: "NOT_FOUND" | "NOT_CONNECTED" };

/**
 * A provider-neutral min/max price range. Mirrors
 * `NormalizedShopifyProduct.priceRange`'s exact shape
 * (`src/lib/shopify-products.ts`) — both bounds are `null` when a product has
 * no priced variants, and `min === max` for a single-price product.
 */
export type CommerceProductPriceRange = {
  min: number | null;
  max: number | null;
};

/**
 * Neutral product shape covering everything the storefront/reward UI reads
 * today. `externalId` replaces provider-specific ids (e.g. Shopify's
 * `shopifyProductGid`) at the neutral boundary — it is ALSO the source for
 * any provider-specific "id" a caller used to read separately: inspecting
 * `src/lib/shopify-products.ts`'s `normalizeProduct` shows Shopify's own
 * `NormalizedShopifyProduct.id` and `.shopifyProductGid` are always the exact
 * same value (`String(product.id)`, assigned to both fields) — there is no
 * second identifier to preserve, so no redundant neutral field is added here.
 * `externalVariantIds` replaces provider-specific variant ids (e.g.
 * Shopify's numeric variant ids, stringified).
 */
/**
 * Raw provider decimal price strings, mirroring
 * `NormalizedShopifyProduct.priceRangeRaw` (`src/lib/shopify-products.ts`) —
 * kept alongside the existing float `priceRange` so a persistence layer can
 * convert to exact integer minor units (via `src/lib/commerce/money.ts`)
 * instead of re-deriving from the already-lossy float value.
 */
export type CommerceProductPriceRangeRaw = {
  min: string | null;
  max: string | null;
};

export type CommerceProduct = {
  externalId: string;
  title: string;
  handle: string | null;
  productUrl: string;
  imageUrl: string | null;
  images: string[];
  priceText: string | null;
  currency: string;
  priceRange: CommerceProductPriceRange;
  externalVariantIds: string[];
  /**
   * Optional additive fields (Phase 3 data acquisition). All are `undefined`
   * unless the underlying provider adapter populates them — existing
   * callers that don't read them are completely unaffected.
   */
  /** Plain-text product description, if the provider exposes one. */
  descriptionText?: string | null;
  /** Product-level SKU (provider-specific derivation; see the Shopify adapter for how it's chosen). */
  sku?: string | null;
  /** Provider-reported lifecycle status (e.g. "ACTIVE" | "DRAFT" | "ARCHIVED"), passed through verbatim. */
  status?: string | null;
  /** When the provider reports the product was created. */
  providerCreatedAt?: Date | null;
  /** When the provider reports the product was last updated. */
  providerUpdatedAt?: Date | null;
  /** Raw decimal price strings — see `CommerceProductPriceRangeRaw`. */
  priceRangeRaw?: CommerceProductPriceRangeRaw;
  /**
   * TRUE only when the provider confirmed the product is published/usable on
   * its merchant storefront. It is never inferred from a URL, product status,
   * handle, inventory, or SQRATCH curation. Deliberately separate from
   * lifecycle availability; a public clickable destination requires both.
   * Undefined means the adapter did not provide complete evidence, which
   * persistence treats as fail-closed false.
   */
  hasProviderStorefrontPublication?: boolean;
  /**
   * TRUE only when `productUrl` itself was returned by the provider. This is
   * navigation provenance, not publication authorization: a passworded dev
   * store can have a published product but require the canonical fallback URL.
   * Sync persists only this boolean (never the raw provider payload) so the
   * click redirect can safely allow a Shopify custom-domain URL while keeping
   * synthesized fallback URLs pinned to the connection's shop domain.
   */
  hasProviderSuppliedStorefrontUrl?: boolean;
};

/**
 * Result of a product sync. Products are always fetched live and never
 * persisted (there is no Product table) — "sync" means "fetch, normalize,
 * and report a timestamp", not "reconcile against stored rows".
 *
 * `hasNextPage` / `limit` mirror `fetchNormalizedShopifyProducts`'s own
 * pagination signal (`src/lib/shopify-products.ts`) so a route's `meta`
 * response field can be reproduced without reaching past this neutral type
 * back into a provider-specific result shape.
 */
export type ProductSyncResult = {
  connectionId: string;
  provider: CommerceProvider;
  products: CommerceProduct[];
  productCount: number;
  syncedAt: Date;
  hasNextPage: boolean;
  limit: number;
};

/**
 * Provider-neutral request for one catalog page. `cursor` is opaque: callers
 * must only return a value previously supplied by the same adapter, never
 * inspect or construct it from provider-specific page-info data.
 */
export type ProductSyncPageRequest = {
  cursor?: string | null;
  limit?: number;
  /** Cancels an in-flight provider request when the logical sync expires. */
  signal?: AbortSignal;
  /**
   * Opaque provider-owned context prepared once for the logical catalog sync.
   * Business code must never inspect or construct it. It exists so a provider
   * can safely gather catalog-wide facts (such as storefront publication)
   * exactly once instead of re-fetching them for every product page.
   */
  syncContext?: unknown;
};

/**
 * Bounds and cancellation shared with an optional provider preparation step.
 * The returned context remains opaque to the neutral sync service.
 */
export type ProductSyncPreparationRequest = {
  limit?: number;
  maxPages?: number;
  maxProducts?: number;
  signal?: AbortSignal;
};

/**
 * One provider-neutral catalog page. A complete page MUST have
 * `nextCursor: null`; an incomplete page MUST provide a non-empty opaque
 * cursor. This deliberately exposes no provider GraphQL page-info shape.
 */
export type ProductSyncPageResult = {
  products: CommerceProduct[];
  nextCursor: string | null;
  isComplete: boolean;
  fetchedAt: Date;
  limit: number;
};

/**
 * Neutral input for creating a provider discount code. Mirrors the fields
 * `createShopifyRewardDiscountCode` accepts today, generalized so a future
 * provider (Commerce7, etc.) could implement the same shape.
 */
export type CreateDiscountInput = {
  code: string;
  title: string;
  issuedAt: Date;
  validDays: number;
  discountType: "FIXED_AMOUNT" | "PERCENTAGE";
  discountAmountCents: number | null;
  discountPercentageBasisPoints: number | null;
  appliesTo: "ALL_PRODUCTS" | "SPECIFIC_PRODUCTS";
  externalProductIds?: string[];
  minimumSubtotalCents?: number | null;
};

/**
 * Optional per-call options for `CommerceAdapter.createDiscount`. Kept
 * separate from `CreateDiscountInput` (which is the discount's own business
 * data) because this is caller-transport plumbing, not part of the discount
 * itself.
 *
 * `preResolvedAccessToken`: when the caller has ALREADY resolved a valid
 * provider access token for this connection's brand (e.g.
 * `src/app/api/rewards/shopify/redeem/route.ts` resolves one via
 * `getValidAccessToken` up front — on the money path — so it can react to a
 * NEEDS_RECONNECT/NOT_CONNECTED failure with its own refund-and-respond
 * branch before ever calling the adapter), passing it here tells the
 * adapter to use it as-is instead of resolving its own. This is what avoids
 * a SECOND, independent token resolution: for Shopify's expiring-offline
 * mode a second resolution is not merely wasteful, it can race the DB
 * compare-and-swap refresh lock or trigger a second refresh attempt against
 * the same brand. When omitted, the adapter resolves its own token exactly
 * as it always has.
 */
export type CreateDiscountOptions = {
  preResolvedAccessToken?: string;
};

/**
 * Neutral discount result. Field selection matches exactly what
 * `src/app/api/rewards/shopify/redeem/route.ts` persists today
 * (`shopifyDiscountNodeId`, `code`, `expiresAt` on `ShopifyRewardRedemption`)
 * — no additional fields are included since nothing currently consumes
 * them.
 */
export type ProviderDiscount = {
  externalDiscountId: string;
  code: string;
  expiresAt: Date | null;
};

/** Opaque provider identifiers in, normalized discount facts out. */
export type GetDiscountInput = {
  externalDiscountId?: string;
  code?: string;
};

/** Transport-only option; the token must already be bound to connectionId. */
export type GetDiscountOptions = {
  preResolvedAccessToken?: string;
};

export type ProviderDiscountLookup =
  | {
      exists: true;
      externalDiscountId: string;
      externalStatus: string | null;
      usageCount: number;
      expiresAt: Date | null;
    }
  | { exists: false };

/** Framework-neutral webhook request input — deliberately not `NextRequest`. */
export type WebhookRequestInput = {
  rawBody: string;
  headers: Record<string, string>;
};

/**
 * Neutral event kinds corresponding to the webhook topics handled today
 * (see `src/lib/shopify-webhooks.ts` and its GDPR/mandatory topics:
 * app/uninstalled, shop/redact, customers/data_request, customers/redact).
 */
export type CommerceWebhookEventType =
  | "APP_UNINSTALLED"
  | "ACCOUNT_REDACT"
  | "CUSTOMER_DATA_REQUEST"
  | "CUSTOMER_REDACT";

/** A verified, provider-neutral webhook event. `payload` is intentionally `unknown`, never `any`. */
export type NormalizedWebhookEvent = {
  provider: CommerceProvider;
  type: CommerceWebhookEventType;
  externalAccountId: string;
  receivedAt: Date;
  payload: unknown;
};
