"use client";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { formatRewardMoney } from "@/lib/reward-formatting";
import { fetchJson, getErrorMessage } from "@/components/experience/client-utils";

type Offer = { currencyCode: string; id: string; title: string; description: string | null; isActive: boolean; rewardMode: "DISCOUNT" | "EXCLUSIVE_PRODUCT_ACCESS"; pointsCost: number; discountType: "FIXED_AMOUNT" | "PERCENTAGE"; discountAmountCents: number | null; discountPercentageBasisPoints: number | null; minimumSubtotalCents: number | null; maxTotalRedemptions: number; maxRedemptionsPerUser: number; codeValidDays: number; claimStartsAt: string | null; claimEndsAt: string | null; commerce7Config: { templateCouponId: string | null; discountEnabled?: boolean }; products: { externalProductId: string }[]; totalClaims: number; issuedCount: number; _count: { redemptions: number } };
type Claim = { id: string; title: string; status: string; provisioningState: string; providerCustomerId: string | null; providerTagId: string | null; tagTitle: string; message: string | null; ownerActive: boolean; canRevoke: boolean; canonicalOrderId: string | null };
export type Commerce7BrandRewardData = { providers: { SHOPIFY: boolean; COMMERCE7: boolean }; connection: { currencyCode: string | null; displayName: string; status: string } | null; readiness: { backendConfigured: boolean }; offers: Offer[]; claims: Claim[]; products: { externalId: string; title: string }[] };
type Form = { discountEnabled: boolean; title: string; description: string; isActive: boolean; rewardMode: Offer["rewardMode"]; pointsCost: string; discountType: Offer["discountType"]; amount: string; percent: string; minimum: string; maxTotal: string; maxUser: string; validDays: string; starts: string; ends: string; templateId: string; productIds: string[] };
const initial: Form = { discountEnabled: true, title: "", description: "", isActive: false, rewardMode: "DISCOUNT", pointsCost: "100", discountType: "FIXED_AMOUNT", amount: "10.00", percent: "15", minimum: "", maxTotal: "25", maxUser: "1", validDays: "30", starts: "", ends: "", templateId: "", productIds: [] };
function cents(value: string) { return /^\d+(\.\d{1,2})?$/.test(value) ? Number(value.split(".")[0]) * 100 + Number((value.split(".")[1] ?? "").padEnd(2, "0")) : NaN; }
function localDate(value: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export function Commerce7BrandRewardsPanel() {
  const running = useRef(false);
  const [data, setData] = useState<Commerce7BrandRewardData | null>(null);
  const [form, setForm] = useState(initial); const [editing, setEditing] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load() { try { setData(await fetchJson<Commerce7BrandRewardData>("/api/brand/rewards/commerce7")); } catch (e) { setError(getErrorMessage(e, "Could not load Commerce7 rewards.")); } }
  useEffect(() => { void load(); }, []);
  const field = (key: keyof Form, value: string | boolean | string[]) => setForm((current) => ({ ...current, [key]: value }));
  async function action(work: () => Promise<unknown>, success: string) { if (running.current) return; running.current = true; setBusy(true); setError(null); setMessage(null); try { await work(); setMessage(success); await load(); } catch (e) { setError(getErrorMessage(e, "Reward action failed.")); } finally { running.current = false; setBusy(false); } }
  async function save() {
    await action(async () => {
      const body = { provider: "COMMERCE7", title: form.title, description: form.description, isActive: form.isActive, rewardMode: form.rewardMode, pointsCost: Number(form.pointsCost), discountType: form.discountType, discountEnabled: form.discountEnabled, discountAmountCents: form.discountEnabled && form.discountType === "FIXED_AMOUNT" ? cents(form.amount) : null, discountPercentageBasisPoints: form.discountEnabled && form.discountType === "PERCENTAGE" ? Number(form.percent) * 100 : null, minimumSubtotalCents: form.minimum ? cents(form.minimum) : null, maxTotalRedemptions: Number(form.maxTotal), maxRedemptionsPerUser: Number(form.maxUser), codeValidDays: Number(form.validDays), claimStartsAt: form.starts ? new Date(form.starts).toISOString() : null, claimEndsAt: form.ends ? new Date(form.ends).toISOString() : null, templateCouponId: form.templateId.trim(), productIds: form.productIds };
      await fetchJson(`/api/brand/rewards/offers${editing ? `/${editing}` : ""}`, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      setEditing(null); setForm(initial);
    }, "Commerce7 reward saved.");
  }
  function edit(offer: Offer) { setEditing(offer.id); setForm({ discountEnabled: offer.commerce7Config.discountEnabled ?? true, title: offer.title, description: offer.description ?? "", isActive: offer.isActive, rewardMode: offer.rewardMode, pointsCost: String(offer.pointsCost), discountType: offer.discountType, amount: ((offer.discountAmountCents ?? 0) / 100).toFixed(2), percent: String((offer.discountPercentageBasisPoints ?? 1500) / 100), minimum: offer.minimumSubtotalCents ? (offer.minimumSubtotalCents / 100).toFixed(2) : "", maxTotal: String(offer.maxTotalRedemptions), maxUser: String(offer.maxRedemptionsPerUser), validDays: String(offer.codeValidDays), starts: localDate(offer.claimStartsAt), ends: localDate(offer.claimEndsAt), templateId: offer.commerce7Config.templateCouponId ?? "", productIds: offer.products.map((p) => p.externalProductId) }); }
  if (!data) return <p role="status">{error ?? "Loading Commerce7 rewards…"}</p>;
  return <div className="space-y-6 p-4 md:p-6">
    <div><h1 className="text-2xl font-semibold">Commerce7 rewards</h1><p className="mt-2 text-sm text-muted-foreground">{data.connection?.displayName ?? "Connect Commerce7 to get started"} · {data.connection?.currencyCode ?? "Currency needs sync"}</p></div>
    <div className="rounded-xl border p-4 text-sm space-y-2"><p>Each reward uses a unique coupon restricted to its claimant’s Customer tag. The customer must use the same verified email in SQRATCH and Commerce7.</p><p>The store must assign each claim’s tag in Commerce7 CRM before the coupon is issued. Coupon: Full, Tag: Full, Customer: Read, Product: Read and Order: Read are required.</p><p>Create a native coupon template with one manual Customer tag, one use per store, no shipping discount, and the desired product scope. Enter its ID below. SQRATCH reads its exact native eligibility and scope settings.</p>{!data.readiness.backendConfigured && <p className="text-destructive">Commerce7 backend credentials are missing. Rewards cannot be issued.</p>}<p>Exclusive wine access can be saved as a draft. Activation is unavailable until Commerce7 confirms the customer access contract. Claiming a discount does not reserve inventory or purchase wine.</p></div>
    {error && <p role="alert" className="text-destructive">{error}</p>}{message && <p role="status">{message}</p>}
    <form onSubmit={(event) => { event.preventDefault(); void save(); }} className="rounded-xl border p-4 space-y-4">
      <h2 className="text-lg font-medium">{editing ? "Edit reward" : "Create reward"}</h2>
      <div className="grid gap-4 md:grid-cols-2">
        <label>Title<Input required maxLength={120} value={form.title} onChange={(e) => field("title", e.target.value)} /></label>
        <label>Reward mode<select className="w-full rounded border p-2" value={form.rewardMode} onChange={(e) => { field("rewardMode", e.target.value); field("discountEnabled", e.target.value === "DISCOUNT"); field("isActive", false); }}><option value="DISCOUNT">Discount</option><option value="EXCLUSIVE_PRODUCT_ACCESS">Exclusive wine access (draft only)</option></select></label>
        <label>Points cost<Input type="number" min={1} step={1} required value={form.pointsCost} onChange={(e) => field("pointsCost", e.target.value)} /></label>
        {form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" && <label className="flex items-center gap-2"><input type="checkbox" checked={form.discountEnabled} onChange={(e) => field("discountEnabled", e.target.checked)} />Include an optional discount</label>}
        {form.discountEnabled && <label>Discount<select className="w-full rounded border p-2" value={form.discountType} onChange={(e) => field("discountType", e.target.value)}><option value="FIXED_AMOUNT">Fixed amount ({data.connection?.currencyCode})</option><option value="PERCENTAGE">Percentage</option></select></label>}
        {form.discountEnabled && (form.discountType === "FIXED_AMOUNT" ? <label>Amount ({data.connection?.currencyCode})<Input type="number" min="0.01" step="0.01" required value={form.amount} onChange={(e) => field("amount", e.target.value)} /></label> : <label>Percentage<Input type="number" min={1} max={100} step={1} required value={form.percent} onChange={(e) => field("percent", e.target.value)} /></label>)}
        {form.discountEnabled && <label>Minimum subtotal (optional)<Input type="number" min="0.01" step="0.01" value={form.minimum} onChange={(e) => field("minimum", e.target.value)} /></label>}
        <label>Total claim limit<Input type="number" min={1} max={form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? 25 : 1000} required value={form.maxTotal} onChange={(e) => field("maxTotal", e.target.value)} /></label>
        <label>Claims per user<Input type="number" min={1} required value={form.maxUser} onChange={(e) => field("maxUser", e.target.value)} /></label>
        <label>Claim starts (local time)<Input type="datetime-local" value={form.starts} onChange={(e) => field("starts", e.target.value)} /></label>
        <label>Claim ends (local time)<Input type="datetime-local" value={form.ends} onChange={(e) => field("ends", e.target.value)} /></label>
        <label>Coupon validity after claim (days)<Input type="number" min={1} max={365} required value={form.validDays} onChange={(e) => field("validDays", e.target.value)} /></label>
        <label>Native coupon template ID{!form.discountEnabled && " (optional for access-only drafts)"}<Input required={form.discountEnabled} value={form.templateId} onChange={(e) => field("templateId", e.target.value)} /></label>
      </div>
      <label className="block">Description<Textarea maxLength={2000} value={form.description} onChange={(e) => field("description", e.target.value)} /></label>
      <label className="block">Product scope (none selects the whole store)<select multiple className="mt-2 w-full rounded border p-2 min-h-24" value={form.productIds} onChange={(e) => field("productIds", Array.from(e.target.selectedOptions, (option) => option.value))}>{data.products.map((p) => <option key={p.externalId} value={p.externalId}>{p.title}</option>)}</select></label>
      <label className="flex gap-2"><input type="checkbox" disabled={form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS"} checked={form.isActive} onChange={(e) => field("isActive", e.target.checked)} />Active and open for claims</label>
      <div className="flex flex-wrap gap-2"><Button disabled={busy || !data.providers.COMMERCE7}>Save reward</Button>{editing && <Button type="button" variant="outline" onClick={() => { setEditing(null); setForm(initial); }}>Cancel edit</Button>}</div>
    </form>
    <section className="space-y-3"><h2 className="text-lg font-medium">Offers</h2>{!data.offers.length && <p>No Commerce7 rewards yet.</p>}{data.offers.map((offer) => <div key={offer.id} className="rounded-xl border p-4 flex flex-wrap justify-between gap-3"><div className="min-w-0 flex-1 break-words"><p className="font-medium">{offer.title} · {offer.isActive ? "Active" : "Inactive"}</p><p className="text-sm">{offer.pointsCost} points · {offer.totalClaims}/{offer.maxTotalRedemptions} reserved or issued · {offer.issuedCount} issued</p><p className="text-sm">{Math.max(0, offer.maxTotalRedemptions - offer.totalClaims)} claims remaining · up to {offer.maxRedemptionsPerUser} per user</p><p className="text-sm">{offer.commerce7Config.discountEnabled === false ? "Access only" : offer.discountType === "PERCENTAGE" ? `${(offer.discountPercentageBasisPoints ?? 0) / 100}% off` : `${formatRewardMoney(offer.discountAmountCents, offer.currencyCode)} off`} · {offer.claimStartsAt ? new Date(offer.claimStartsAt).toLocaleString() : "No start limit"} – {offer.claimEndsAt ? new Date(offer.claimEndsAt).toLocaleString() : "No end limit"}</p>{offer.products.length > 0 && <p className="text-sm">Products: {offer.products.map((product) => data.products.find((row) => row.externalId === product.externalProductId)?.title ?? product.externalProductId).join(", ")}</p>}<p className="text-sm">{offer.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? "Exclusive access requires provider contract confirmation." : "Customer tag assignment required for each claim."}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || offer._count.redemptions > 0} onClick={() => edit(offer)}>Edit</Button><Button variant="outline" disabled={busy || !offer.isActive} onClick={() => void action(() => fetchJson(`/api/brand/rewards/offers/${offer.id}`, { method: "PATCH" }), "Offer disabled. Existing claims retain their terms.")}>Disable</Button></div></div>)}</section>
    <section className="space-y-3"><div className="flex justify-between"><h2 className="text-lg font-medium">Recent claims and provider setup</h2><Button variant="outline" disabled={busy} onClick={() => void load()}>Refresh</Button></div>{!data.claims.length && <p>No claims yet.</p>}{data.claims.map((claim) => <div key={claim.id} className="rounded-xl border p-4 space-y-2 text-sm break-words"><p className="font-medium">{claim.title} · {claim.status} · {claim.provisioningState.replaceAll("_", " ")}</p>{claim.provisioningState === "AWAITING_ELIGIBILITY" && <p>In Commerce7 CRM, open customer {claim.providerCustomerId} and add the manual tag {claim.tagTitle} ({claim.providerTagId}). Confirm the customer uses the claimant’s verified email. Apply this tag only to that customer, then check again.</p>}{claim.message && <p>{claim.message}</p>}{claim.canRevoke && <p>Revoking removes this coupon. Issued claim capacity stays consumed; points require a separately reviewed adjustment.</p>}{claim.ownerActive && <p>Worker ownership is held. Follow the operator recovery procedure if the worker stopped.</p>}{claim.canonicalOrderId && <p>Purchase linked to SQRATCH order {claim.canonicalOrderId}. Financial and refund totals remain in Orders.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || claim.ownerActive || claim.status !== "POINTS_DEBITED"} onClick={() => void action(() => fetchJson(`/api/brand/rewards/commerce7/claims/${claim.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "RETRY" }) }), "Claim checked.")}>Check provider result</Button>{claim.canRevoke && <Button variant="outline" disabled={busy} onClick={() => void action(() => fetchJson(`/api/brand/rewards/commerce7/claims/${claim.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "REVOKE" }) }), "Coupon revoked. Issued claim capacity is retained; points are not automatically refunded.")}>Revoke coupon</Button>}</div></div>)}</section>
  </div>;
}
