"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import type { Commerce7RewardEligibility } from "@/lib/commerce7-reward-eligibility";
import { commerce7CouponSupport } from "@/lib/commerce7-coupon-contract";
import { Textarea } from "@/components/ui/textarea";
import { formatRewardMoney } from "@/lib/reward-formatting";
import { fetchJson, getErrorMessage } from "@/components/experience/client-utils";

type Offer = { appliesTo: "ALL_PRODUCTS" | "SPECIFIC_PRODUCTS"; currencyCode: string; id: string; title: string; description: string | null; isActive: boolean; rewardMode: "DISCOUNT" | "EXCLUSIVE_PRODUCT_ACCESS"; pointsCost: number; discountType: "FIXED_AMOUNT" | "PERCENTAGE"; discountAmountCents: number | null; discountPercentageBasisPoints: number | null; minimumSubtotalCents: number | null; maxTotalRedemptions: number; maxRedemptionsPerUser: number; codeValidDays: number; claimStartsAt: string | null; claimEndsAt: string | null; commerce7Config: { eligibilityMode?: Commerce7RewardEligibility | null; discountEnabled?: boolean; exclusiveTagTitle?: string | null }; products: { externalProductId: string }[]; totalClaims: number; issuedCount: number; editable?: boolean; exclusiveAccessStatus?: keyof typeof EXCLUSIVE_STATUS_TEXT | null; exclusiveTagCount?: number; exclusiveSharedProductCount?: number; _count: { redemptions: number } };
type AccessState = "ACCESS_GRANTED" | "ALREADY_ELIGIBLE" | "WAITING_FOR_CUSTOMER" | "CONFIRMATION_PENDING" | "PROCESSING" | "MANUAL_REVIEW" | "FAILED";
type Claim = { id: string; title: string; status: string; provisioningState: string; providerCustomerId: string | null; providerTagId: string | null; tagTitle: string | null; message: string | null; ownerActive: boolean; canRevoke: boolean; canonicalOrderId: string | null; rewardMode?: Offer["rewardMode"]; accessState?: AccessState | null; membershipGuidance?: keyof typeof MEMBERSHIP_GUIDANCE_TEXT | null };
export type Commerce7BrandRewardData = { providers: { SHOPIFY: boolean; COMMERCE7: boolean }; connection: { currencyCode: string | null; displayName: string; status: string } | null; readiness: { backendConfigured: boolean; couponContract?: ReturnType<typeof commerce7CouponSupport>; exclusiveMultiTagAccessVerified?: boolean }; offers: Offer[]; claims: Claim[]; products: { externalId: string; title: string }[]; exclusiveProducts?: { externalId: string; title: string; tagCount?: number }[] };
/** One Customer Tag securing the chosen product, resolved live by the server. `id` is only the selector value; never shown. */
type TagOption = { id: string; title: string | null; selectable: boolean; current: boolean; reason: "NOT_FOUND" | "NOT_MANUAL" | "NOT_CUSTOMER" | null; sharedProductCount: number; sharedProductTitles: string[] };
type TagOptions = { productId: string; tagCount: number; multiTagAccessVerified: boolean; preselectedTagId: string | null; tags: TagOption[] };
type Form = { appliesTo: Offer["appliesTo"]; eligibilityMode: Commerce7RewardEligibility; discountEnabled: boolean; title: string; description: string; isActive: boolean; rewardMode: Offer["rewardMode"]; pointsCost: string; discountType: Offer["discountType"]; amount: string; percent: string; minimum: string; maxTotal: string; maxUser: string; validDays: string; starts: string; ends: string; productIds: string[]; exclusiveTagId: string };
const initial: Form = { appliesTo: "ALL_PRODUCTS", eligibilityMode: "ANYONE_WITH_CODE", discountEnabled: true, title: "", description: "", isActive: false, rewardMode: "DISCOUNT", pointsCost: "100", discountType: "FIXED_AMOUNT", amount: "10.00", percent: "15", minimum: "", maxTotal: "25", maxUser: "1", validDays: "30", starts: "", ends: "", productIds: [], exclusiveTagId: "" };
/**
 * One atomic reward-mode transition. Every mode-specific field is set from the target mode's defaults, so no exclusive-only
 * state (claimant binding, product scope, hidden product IDs, disabled discount) survives a return to Discount, and nothing is
 * read from a stale render. Common fields (title, description, points, dates, limits, validity) are kept.
 */
function withRewardMode(current: Form, rewardMode: Form["rewardMode"]): Form {
  if (rewardMode === current.rewardMode) return current;
  if (rewardMode === "EXCLUSIVE_PRODUCT_ACCESS") return { ...current, rewardMode, isActive: false, eligibilityMode: "CLAIMANT_ONLY", appliesTo: "SPECIFIC_PRODUCTS", productIds: [], exclusiveTagId: "", discountEnabled: false };
  return { ...current, rewardMode: "DISCOUNT", isActive: false, eligibilityMode: "ANYONE_WITH_CODE", appliesTo: "ALL_PRODUCTS", productIds: [], exclusiveTagId: "", discountEnabled: true, discountType: current.discountType === "PERCENTAGE" ? "PERCENTAGE" : "FIXED_AMOUNT" };
}
const EXCLUSIVE_STATUS_TEXT = {
  CONFIGURED: "Ready: the product is secured to the selected Customer Tag in Commerce7.",
  MULTI_TAG_UNVERIFIED: "This product is secured to several Customer Tags. Access for multi-tag products has not been verified, so this reward stays a draft.",
  TAG_REMOVED: "The selected Customer Tag no longer secures this product in Commerce7. Choose a current tag, sync products, then re-save this reward.",
  SECURITY_CHANGED: "Product security changed in Commerce7. Secure it to a Customer Tag, sync products, then re-save this reward.",
  PRODUCT_UNAVAILABLE: "The exclusive product is no longer synchronized and available. Sync products, then re-save this reward.",
  NOT_CONFIGURED: "Choose a product secured to a Customer Tag in Commerce7 and the tag SQRATCH should grant.",
} as const;
const ACCESS_STATE_TEXT: Record<AccessState, string> = {
  ACCESS_GRANTED: "Access granted: the customer holds the Customer Tag in Commerce7.", ALREADY_ELIGIBLE: "Already eligible in Commerce7: no points were kept and SQRATCH did not change the customer's tags.",
  WAITING_FOR_CUSTOMER: "Waiting for a Commerce7 customer with the claimant's verified email.", CONFIRMATION_PENDING: "Commerce7 accepted the grant; waiting for it to confirm the tag.",
  PROCESSING: "Being processed.", MANUAL_REVIEW: "Store review needed. Check the customer's tags in Commerce7, then use Check provider result. SQRATCH never sends a second grant after an unclear result.", FAILED: "Closed without access. Any points were returned.",
};
const MEMBERSHIP_GUIDANCE_TEXT = {
  NOT_SQRATCH_OWNED: "The customer already had this tag before the claim. It is not SQRATCH's; do not remove it on account of this reward.",
  OWNERSHIP_UNVERIFIED: "The tag is present, but SQRATCH cannot prove it created it (its request had an unclear result). Treat it as the store's.",
  SHARED_WITH_OTHER_REWARDS: "SQRATCH granted this tag, and another active SQRATCH reward also relies on it for this customer.",
  SQRATCH_GRANTED: "SQRATCH granted this tag.",
} as const;
const TAG_REASON_TEXT = { NOT_FOUND: "no longer exists in Commerce7", NOT_MANUAL: "not a Manual tag", NOT_CUSTOMER: "not a Customer tag" } as const;
function cents(value: string) { return /^\d+(\.\d{1,2})?$/.test(value) ? Number(value.split(".")[0]) * 100 + Number((value.split(".")[1] ?? "").padEnd(2, "0")) : NaN; }
function localDate(value: string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
export function Commerce7BrandRewardsPanel() {
  const running = useRef(false);
  const loadSequence = useRef(0);
  const [productSearch, setProductSearch] = useState("");
  const [data, setData] = useState<Commerce7BrandRewardData | null>(null);
  const [form, setForm] = useState(initial); const [editing, setEditing] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [tagOptions, setTagOptions] = useState<TagOptions | null>(null); const [tagError, setTagError] = useState<string | null>(null); const tagSequence = useRef(0);
  async function load() { const sequence = ++loadSequence.current; try { const value = await fetchJson<Commerce7BrandRewardData>("/api/brand/rewards/commerce7"); if (sequence === loadSequence.current) setData(value); } catch (e) { if (sequence === loadSequence.current) setError(getErrorMessage(e, "Could not load Commerce7 rewards.")); } }
  const invalidateLoad = useCallback(() => { loadSequence.current++; }, []);
  useEffect(() => { void load(); return invalidateLoad; }, [invalidateLoad]);
  // The server owns which coupon branches may go live. Until it says so, anything unverified stays draft-only.
  const support = data?.readiness.couponContract ?? commerce7CouponSupport();
  const branchLive = (value: Form) => support.eligibility[value.eligibilityMode] === true && support.scope[value.appliesTo] === true;
  const field = (key: keyof Form, value: string | boolean | string[]) => setForm((current) => {
    const next = { ...current, [key]: value, ...(key === "appliesTo" && value === "ALL_PRODUCTS" ? { productIds: [] } : {}) } as Form;
    return (key === "eligibilityMode" || key === "appliesTo") && !branchLive(next) ? { ...next, isActive: false } : next;
  });
  async function action(work: () => Promise<unknown>, success: string) { if (running.current) return; running.current = true; setBusy(true); setError(null); setMessage(null); try { await work(); setMessage(success); await load(); } catch (e) { setError(getErrorMessage(e, "Reward action failed.")); } finally { running.current = false; setBusy(false); } }
  async function save() {
    await action(async () => {
      if (form.appliesTo === "SPECIFIC_PRODUCTS" && !form.productIds.length) throw new Error("Select at least one product.");
      if (form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" && !form.exclusiveTagId) throw new Error("Choose which Customer Tag SQRATCH should grant.");
      // NaN serializes to null, which would silently drop a minimum or defer a bad amount to the server. Reject it here.
      const amountCents = form.discountEnabled && form.discountType === "FIXED_AMOUNT" ? cents(form.amount) : null;
      const minimumCents = form.discountEnabled && form.minimum ? cents(form.minimum) : null;
      if (Number.isNaN(amountCents)) throw new Error("Enter the amount in dollars with at most two decimals.");
      if (Number.isNaN(minimumCents)) throw new Error("Enter the minimum subtotal in dollars with at most two decimals.");
      const body = { appliesTo: form.appliesTo, eligibilityMode: form.eligibilityMode, provider: "COMMERCE7", title: form.title, description: form.description, isActive: form.isActive, rewardMode: form.rewardMode, pointsCost: Number(form.pointsCost), discountType: form.discountType, discountEnabled: form.discountEnabled, discountAmountCents: amountCents, discountPercentageBasisPoints: form.discountEnabled && form.discountType === "PERCENTAGE" ? Number(form.percent) * 100 : null, minimumSubtotalCents: minimumCents, maxTotalRedemptions: Number(form.maxTotal), maxRedemptionsPerUser: Number(form.maxUser), codeValidDays: Number(form.validDays), claimStartsAt: form.starts ? new Date(form.starts).toISOString() : null, claimEndsAt: form.ends ? new Date(form.ends).toISOString() : null, productIds: form.appliesTo === "ALL_PRODUCTS" ? [] : form.productIds, ...(form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? { exclusiveTagId: form.exclusiveTagId } : {}) };
      await fetchJson(`/api/brand/rewards/offers${editing ? `/${editing}` : ""}`, { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      setEditing(null); setForm(initial);
    }, "Commerce7 reward saved.");
  }
  function edit(offer: Offer) { if (running.current) return; setProductSearch(""); setEditing(offer.id); setForm({ appliesTo: offer.appliesTo ?? (offer.products.length ? "SPECIFIC_PRODUCTS" : "ALL_PRODUCTS"), eligibilityMode: offer.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? "CLAIMANT_ONLY" : offer.commerce7Config.eligibilityMode ?? "CLAIMANT_ONLY", discountEnabled: offer.commerce7Config.discountEnabled ?? true, title: offer.title, description: offer.description ?? "", isActive: offer.isActive, rewardMode: offer.rewardMode, pointsCost: String(offer.pointsCost), discountType: offer.discountType, amount: ((offer.discountAmountCents ?? 0) / 100).toFixed(2), percent: String((offer.discountPercentageBasisPoints ?? 1500) / 100), minimum: offer.minimumSubtotalCents ? (offer.minimumSubtotalCents / 100).toFixed(2) : "", maxTotal: String(offer.maxTotalRedemptions), maxUser: String(offer.maxRedemptionsPerUser), validDays: String(offer.codeValidDays), starts: localDate(offer.claimStartsAt), ends: localDate(offer.claimEndsAt), productIds: offer.products.map((p) => p.externalProductId), exclusiveTagId: "" }); }
  // Exclusive access only offers products the server verified are secured to exactly one Customer Tag; security data never reaches the browser.
  const exclusive = form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS";
  const pickerProducts: { externalId: string; title: string; tagCount?: number }[] = exclusive ? data?.exclusiveProducts ?? [] : data?.products ?? [];
  const exclusiveProductId = exclusive ? form.productIds[0] ?? null : null;
  // The chosen product's Customer Tags, resolved live by the server. A later product choice wins over a late response.
  useEffect(() => {
    const sequence = ++tagSequence.current; setTagOptions(null); setTagError(null);
    if (!exclusiveProductId) return;
    const query = new URLSearchParams({ productId: exclusiveProductId }); if (editing) query.set("offerId", editing);
    fetchJson<Omit<TagOptions, "productId">>(`/api/brand/rewards/commerce7/exclusive-tags?${query}`).then((value) => {
      if (sequence !== tagSequence.current) return;
      setTagOptions({ ...value, productId: exclusiveProductId });
      // A single-tag product (or an edited offer's current tag) is preselected; several tags always need an explicit choice.
      setForm((current) => current.productIds[0] === exclusiveProductId && !current.exclusiveTagId && value.preselectedTagId ? { ...current, exclusiveTagId: value.preselectedTagId } : current);
    }).catch((e) => { if (sequence === tagSequence.current) setTagError(getErrorMessage(e, "Could not load this product's Customer Tags.")); });
  }, [exclusiveProductId, editing]);
  const tagsLoaded = tagOptions?.productId === exclusiveProductId ? tagOptions : null;
  const selectedTag = tagsLoaded?.tags.find((tag) => tag.id === form.exclusiveTagId && tag.selectable) ?? null;
  const multiTagBlocked = !!tagsLoaded && tagsLoaded.tagCount > 1 && !tagsLoaded.multiTagAccessVerified;
  const exclusiveActivatable = exclusive && !!selectedTag && !multiTagBlocked;
  if (!data) return <p role="status">{error ?? "Loading Commerce7 rewards…"}</p>;
  return <div className="space-y-6 p-4 md:p-6">
    <div><h1 className="text-2xl font-semibold">Commerce7 rewards</h1><p className="mt-2 text-sm text-muted-foreground">{data.connection?.displayName ?? "Connect Commerce7 to get started"} · {data.connection?.currencyCode ?? "Currency needs sync"}</p></div>
    <div className="rounded-xl border p-4 text-sm space-y-2"><p>For standard Commerce7 discount rewards, no Commerce7 coupon needs to be created manually. Configure the reward here. SQRATCH creates the claim’s single-use native Commerce7 coupon when points are redeemed.</p><p>Anyone with the code: fully automatic. A unique, single-use coupon with no Commerce7 account matching, Customer tag or CRM setup.</p><p>Claiming customer only: uses the same verified email in SQRATCH and Commerce7 and a unique Customer tag per claim. The store still assigns each claim’s tag in CRM before issuance. This option is draft-only until it is verified for your store.</p><p>Coupon: Full is required. Customer-bound rewards also need Tag: Full and Customer: Read. Product: Read and Order: Read support catalog validation and purchase reconciliation.</p>{!data.readiness.backendConfigured && <p className="text-destructive">Commerce7 backend credentials are missing. Rewards cannot be issued.</p>}<p>Selected products: the coupon is limited to the exact synchronized products you choose.</p><p>Exclusive wine access grants Commerce7 storefront access: when a member claims it, SQRATCH adds one existing Manual Customer Tag (the one you choose) to the member&apos;s Commerce7 customer with the same verified email. The member then logs in to your Commerce7 store to buy. SQRATCH never changes product security, never creates or deletes tags, and never removes a tag from a customer. A customer who already has the tag is not charged for access-only rewards. Commerce7 product security applies to website purchases; POS and inbound carts are not restricted by a Customer Tag. Claiming does not reserve inventory or purchase wine, and a coupon is not required to buy the secured wine.</p></div>
    {error && <p role="alert" className="text-destructive">{error}</p>}{message && <p role="status">{message}</p>}
    <form onSubmit={(event) => { event.preventDefault(); void save(); }} className="rounded-xl border p-4 space-y-4">
      <h2 className="text-lg font-medium">{editing ? "Edit reward" : "Create reward"}</h2>
      <fieldset disabled={busy} className="space-y-4">
      <div className="grid gap-4 md:grid-cols-2">
        <label>Title<Input required maxLength={120} value={form.title} onChange={(e) => field("title", e.target.value)} /></label>
        <label>Reward mode<select className="w-full rounded border p-2" value={form.rewardMode} onChange={(e) => { const mode = e.target.value === "EXCLUSIVE_PRODUCT_ACCESS" ? "EXCLUSIVE_PRODUCT_ACCESS" : "DISCOUNT"; setProductSearch(""); setForm((current) => withRewardMode(current, mode)); }}><option value="DISCOUNT">Discount</option><option value="EXCLUSIVE_PRODUCT_ACCESS">Exclusive wine access</option></select></label>
        <label>Eligible customer<select className="w-full rounded border p-2" disabled={form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS"} value={form.eligibilityMode} onChange={(e) => field("eligibilityMode", e.target.value)}><option value="ANYONE_WITH_CODE">Anyone with the code</option><option value="CLAIMANT_ONLY">Claiming customer only{support.eligibility.CLAIMANT_ONLY ? "" : " (draft only)"}</option></select></label>
        <label>Applies to<select className="w-full rounded border p-2" disabled={form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS"} value={form.appliesTo} onChange={(e) => { field("appliesTo", e.target.value); setProductSearch(""); }}><option value="ALL_PRODUCTS">All products</option><option value="SPECIFIC_PRODUCTS">Selected products{support.scope.SPECIFIC_PRODUCTS ? "" : " (draft only)"}</option></select></label>
        <label>Points cost<Input type="number" min={1} step={1} required value={form.pointsCost} onChange={(e) => field("pointsCost", e.target.value)} /></label>
        {form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" && <label className="flex items-center gap-2"><input type="checkbox" checked={form.discountEnabled} onChange={(e) => field("discountEnabled", e.target.checked)} />Include an optional discount</label>}
        {form.discountEnabled && <label>Discount<select className="w-full rounded border p-2" value={form.discountType} onChange={(e) => field("discountType", e.target.value)}><option value="FIXED_AMOUNT">Fixed amount ({data.connection?.currencyCode})</option><option value="PERCENTAGE">Percentage</option></select></label>}
        {form.discountEnabled && (form.discountType === "FIXED_AMOUNT" ? <label>Amount ({data.connection?.currencyCode})<Input type="number" min="0.01" step="0.01" required value={form.amount} onChange={(e) => field("amount", e.target.value)} /></label> : <label>Percentage<Input type="number" min={1} max={100} step={1} required value={form.percent} onChange={(e) => field("percent", e.target.value)} /></label>)}
        {form.discountEnabled && <label>Minimum subtotal (optional)<Input type="number" min="0.01" step="0.01" value={form.minimum} onChange={(e) => field("minimum", e.target.value)} /></label>}
        <label>Total claim limit<Input type="number" min={1} max={form.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? 25 : 1000} required value={form.maxTotal} onChange={(e) => field("maxTotal", e.target.value)} /></label>
        <label>Claims per user<Input type="number" min={1} required value={form.maxUser} onChange={(e) => field("maxUser", e.target.value)} /></label>
        <label>Claim starts (local time)<Input type="datetime-local" value={form.starts} onChange={(e) => field("starts", e.target.value)} /></label>
        <label>Claim ends (local time)<Input type="datetime-local" value={form.ends} onChange={(e) => field("ends", e.target.value)} /></label>
        <label>Coupon validity after claim (days)<Input type="number" min={1} max={365} required value={form.validDays} onChange={(e) => field("validDays", e.target.value)} /></label>
        </div>
      <label className="block">Description<Textarea maxLength={2000} value={form.description} onChange={(e) => field("description", e.target.value)} /></label>
      {form.rewardMode === "DISCOUNT" && !branchLive(form) && <p className="text-sm" role="note">This option can be saved as a draft but cannot be activated yet. Choose Anyone with the code and All products to go live.</p>}
      {exclusive ? <p className="text-sm">Each claim adds the Customer Tag you choose below to the member&apos;s matching Commerce7 customer automatically; no CRM step is needed.</p> : form.eligibilityMode === "CLAIMANT_ONLY" ? <p className="text-sm">This reward requires a matching verified email and manual assignment of a unique Customer tag for each claim.</p> : <p className="text-sm">Anyone with this coupon can redeem it once. No matching Commerce7 email or CRM tag setup is required.</p>}
      {form.appliesTo === "SPECIFIC_PRODUCTS" && <div className="rounded-2xl border p-4 space-y-3">
        <div className="flex items-center justify-between gap-3"><h3 className="font-medium">Selected products ({form.productIds.length})</h3><Button type="button" variant="outline" onClick={() => field("productIds", [])}>Clear selection</Button></div>
        <Input aria-label="Search products" placeholder="Search products" value={productSearch} onChange={(e) => setProductSearch(e.target.value)} />
        {form.productIds.length > 0 && <div className="flex flex-wrap gap-2">{form.productIds.map((id) => <Button key={id} type="button" variant="outline" onClick={() => field("productIds", form.productIds.filter((selected) => selected !== id))}>{pickerProducts.find((product) => product.externalId === id)?.title ?? "Unavailable product"} · Remove</Button>)}</div>}
        {exclusive && <p className="text-sm">Only Commerce7 products secured to a Customer Tag are shown here. Configure the product&apos;s Security in Commerce7 first, then sync products in SQRATCH.</p>}
        <div className="grid max-h-80 gap-3 overflow-y-auto md:grid-cols-2">{pickerProducts.filter((product) => product.title.toLowerCase().includes(productSearch.toLowerCase())).map((product) => <label key={product.externalId} className="flex cursor-pointer items-center gap-3 rounded-2xl border p-3"><Checkbox checked={form.productIds.includes(product.externalId)} onCheckedChange={(checked) => exclusive ? setForm((current) => ({ ...current, productIds: checked === true ? [product.externalId] : [], exclusiveTagId: "", isActive: false })) : field("productIds", checked === true ? [...form.productIds, product.externalId] : form.productIds.filter((id) => id !== product.externalId))} /><span>{product.title}</span>{exclusive && (product.tagCount ?? 1) > 1 && <span className="text-xs text-muted-foreground">{product.tagCount} Customer Tags</span>}</label>)}</div>
        {!pickerProducts.length && <p className="text-sm">{exclusive ? "No eligible exclusive products found. In Commerce7, secure the product to a Customer Tag, save it, then return to SQRATCH → Products and sync." : "No available products. Sync the Commerce7 catalog."}</p>}
        {exclusive && <p className="text-sm">Select exactly one exclusive product.</p>}
        {exclusive && exclusiveProductId && <div className="space-y-2">
          {!tagsLoaded && !tagError && <p className="text-sm" role="status">Loading this product&apos;s Customer Tags from Commerce7…</p>}
          {tagError && <p className="text-sm text-destructive" role="alert">{tagError}</p>}
          {tagsLoaded && <label className="block">Customer Tag SQRATCH grants<select aria-label="Customer Tag SQRATCH grants" className="w-full rounded border p-2" value={form.exclusiveTagId} onChange={(e) => setForm((current) => ({ ...current, exclusiveTagId: e.target.value, isActive: false }))}><option value="">Choose a Customer Tag</option>{tagsLoaded.tags.map((tag) => <option key={tag.id} value={tag.id} disabled={!tag.selectable}>{tag.title ?? "Unnamed tag"}{tag.reason ? ` (${TAG_REASON_TEXT[tag.reason]})` : ""}</option>)}</select></label>}
          {tagsLoaded && tagsLoaded.tagCount > 1 && <p className="text-sm" role="note">This product is secured to {tagsLoaded.tagCount} Customer Tags. Granting one tag may not be the only way to access it: customers who hold any of its other tags may also be able to buy it.{multiTagBlocked ? " Access for multi-tag products has not been verified yet, so this reward can be saved as a draft only." : ""}</p>}
          {selectedTag && selectedTag.sharedProductCount > 0 && <p className="text-sm" role="note">This tag also secures {selectedTag.sharedProductCount} other product{selectedTag.sharedProductCount === 1 ? "" : "s"} ({selectedTag.sharedProductTitles.join(", ")}{selectedTag.sharedProductCount > selectedTag.sharedProductTitles.length ? ", …" : ""}). Granting it may unlock those products too.</p>}
          <p className="text-sm">Members need a Commerce7 customer account with the same verified email they use in SQRATCH, and must log in to your Commerce7 store to buy.</p>
        </div>}
      </div>}
      <label className="flex gap-2"><input type="checkbox" disabled={exclusive ? !exclusiveActivatable && !form.isActive : !branchLive(form) && !form.isActive} checked={form.isActive} onChange={(e) => field("isActive", e.target.checked)} />Active and open for claims</label>
      <div className="flex flex-wrap gap-2"><Button disabled={busy || !data.providers.COMMERCE7}>Save reward</Button>{editing && <Button type="button" variant="outline" disabled={busy} onClick={() => { setEditing(null); setForm(initial); setProductSearch(""); }}>Cancel edit</Button>}</div>
      </fieldset>
    </form>
    <section className="space-y-3"><h2 className="text-lg font-medium">Offers</h2>{!data.offers.length && <p>No Commerce7 rewards yet.</p>}{data.offers.map((offer) => <div key={offer.id} className="rounded-xl border p-4 flex flex-wrap justify-between gap-3"><div className="min-w-0 flex-1 break-words"><p className="font-medium">{offer.title} · {offer.isActive ? "Active" : "Inactive"}</p><p className="text-sm">{offer.pointsCost} points · {offer.totalClaims}/{offer.maxTotalRedemptions} reserved or issued · {offer.issuedCount} issued</p><p className="text-sm">{Math.max(0, offer.maxTotalRedemptions - offer.totalClaims)} claims remaining · up to {offer.maxRedemptionsPerUser} per user</p><p className="text-sm">{offer.commerce7Config.discountEnabled === false ? "Access only" : offer.discountType === "PERCENTAGE" ? `${(offer.discountPercentageBasisPoints ?? 0) / 100}% off` : `${formatRewardMoney(offer.discountAmountCents, offer.currencyCode)} off`} · {offer.claimStartsAt ? new Date(offer.claimStartsAt).toLocaleString() : "No start limit"} – {offer.claimEndsAt ? new Date(offer.claimEndsAt).toLocaleString() : "No end limit"}</p>{offer.products.length > 0 && <p className="text-sm">Products: {offer.products.map((product) => data.products.find((row) => row.externalId === product.externalProductId)?.title ?? product.externalProductId).join(", ")}</p>}<p className="text-sm">{offer.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" ? `Exclusive Commerce7 storefront access${offer.commerce7Config.exclusiveTagTitle ? ` · grants Customer Tag “${offer.commerce7Config.exclusiveTagTitle}”` : ""}. ${EXCLUSIVE_STATUS_TEXT[offer.exclusiveAccessStatus ?? "NOT_CONFIGURED"]}` : offer.commerce7Config.eligibilityMode === "ANYONE_WITH_CODE" ? "Anyone with the code · single use" : "Claiming customer only · Customer tag assignment required for each claim."}</p>{offer.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" && (offer.exclusiveSharedProductCount ?? 0) > 0 && <p className="text-sm">This tag also secures {offer.exclusiveSharedProductCount} other synchronized product{offer.exclusiveSharedProductCount === 1 ? "" : "s"}; granting it may unlock them too.</p>}</div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || !(offer.editable ?? offer._count.redemptions === 0)} onClick={() => edit(offer)}>Edit</Button><Button variant="outline" disabled={busy} onClick={() => void action(() => fetchJson(`/api/brand/rewards/offers/${offer.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: offer.isActive ? "DISABLE" : "ENABLE" }) }), offer.isActive ? "Offer disabled. Existing claims retain their terms." : "Offer enabled. Existing claims and issued coupons are unchanged.")}>{offer.isActive ? "Disable" : "Enable"}</Button></div></div>)}</section>
    <section className="space-y-3"><div className="flex justify-between"><h2 className="text-lg font-medium">Recent claims and provider setup</h2><Button variant="outline" disabled={busy} onClick={() => void load()}>Refresh</Button></div>{!data.claims.length && <p>No claims yet.</p>}{data.claims.map((claim) => <div key={claim.id} className="rounded-xl border p-4 space-y-2 text-sm break-words"><p className="font-medium">{claim.title} · {claim.status} · {claim.provisioningState.replaceAll("_", " ")}</p>{claim.rewardMode === "EXCLUSIVE_PRODUCT_ACCESS" && claim.accessState && <p>{ACCESS_STATE_TEXT[claim.accessState]}</p>}{claim.membershipGuidance && <p>{MEMBERSHIP_GUIDANCE_TEXT[claim.membershipGuidance]} SQRATCH never removes Customer Tags. Commerce7 removes every copy of a tag from a customer at once, so check Club, allocation and other uses before removing it in Commerce7.</p>}{claim.rewardMode !== "EXCLUSIVE_PRODUCT_ACCESS" && claim.provisioningState === "AWAITING_ELIGIBILITY" && <p>In Commerce7 CRM, open customer {claim.providerCustomerId} and add the manual tag {claim.tagTitle} ({claim.providerTagId}). Confirm the customer uses the claimant’s verified email. Apply this tag only to that customer, then check again.</p>}{claim.message && <p>{claim.message}</p>}{claim.canRevoke && <p>Revoking removes this coupon. Issued claim capacity stays consumed; points require a separately reviewed adjustment.</p>}{claim.ownerActive && <p>Worker ownership is held. Follow the operator recovery procedure if the worker stopped.</p>}{claim.canonicalOrderId && <p>Purchase linked to SQRATCH order {claim.canonicalOrderId}. Financial and refund totals remain in Orders.</p>}<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || claim.ownerActive || claim.status !== "POINTS_DEBITED"} onClick={() => void action(() => fetchJson(`/api/brand/rewards/commerce7/claims/${claim.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "RETRY" }) }), "Claim checked.")}>Check provider result</Button>{claim.canRevoke && <Button variant="outline" disabled={busy} onClick={() => void action(() => fetchJson(`/api/brand/rewards/commerce7/claims/${claim.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "REVOKE" }) }), "Coupon revoked. Issued claim capacity is retained; points are not automatically refunded.")}>Revoke coupon</Button>}</div></div>)}</section>
  </div>;
}
