import type { LegalDocument } from "@/content/legal/types";

export const privacyPolicy: LegalDocument = {
  eyebrow: "Legal",
  title: "SQRATCH Privacy Policy",
  effectiveDate: "June 1st 2026",
  company: "Sqratch Inc.",
  contact: "support@sqratch.com",
  intro: [
    "SQRATCH requests Shopify permissions needed to provide product display and reward discount functionality. These permissions currently include read_products, read_discounts, and write_discounts. SQRATCH does not request permission to create, edit, or delete Shopify products.",
    "This Privacy Policy explains how SQRATCH collects, uses, stores, and protects information when merchants install the SQRATCH Shopify app or use the SQRATCH platform.",
  ],
  sections: [
    {
      title: "1. Information We Collect",
      paragraphs: [
        "When a merchant installs or connects the SQRATCH Shopify app, we may collect and process the following information:",
      ],
      bullets: [
        "Shopify shop domain",
        "Shopify store identifier",
        "Shopify app installation status",
        "Shopify product information, including product titles, images, prices, variants, handles, and public product URLs",
        "Shopify Admin API access token, stored in encrypted form",
        "SQRATCH account information, such as name, email address, role, and Brand account association",
        "Usage information related to SQRATCH dashboards, product syncing, lessons, experiences, and campaign interactions",
        "Shopify discount and reward information, including discount code identifiers, generated discount code values, discount amounts, applicable products, usage limits, expiration dates, and usage status",
        "SQRATCH reward offer information, including points cost, discount amount, currency, claim window, redemption limits, selected products, and active/inactive status",
        "SQRATCH reward redemption information, including the redeeming user, redeemed points, generated discount code, redemption status, issue date, expiration date, and Shopify discount status",
        "SQRATCH does not request permission to create, edit, or delete Shopify products.",
      ],
    },
    {
      title: "2. Information We Do Not Collect Through Shopify",
      paragraphs: [
        "SQRATCH does not request access to Shopify orders, customer records, payment information, checkout data, shipping addresses, or protected customer data.",
        "SQRATCH does not sell merchant data, Shopify product data, or user data.",
        "SQRATCH does not use Shopify customer-specific discount targeting in its current reward flow. Reward discount codes generated by SQRATCH are single-use codes that may be used once by anyone who has the code.",
      ],
    },
    {
      title: "3. How We Use Information",
      paragraphs: ["SQRATCH uses collected information to:"],
      bullets: [
        "Connect a Shopify store to a SQRATCH Brand account",
        "Fetch and display Shopify product information inside SQRATCH",
        "Allow approved Brand Admins and Creators to link products to SQRATCH experiences and lessons",
        "Display public Shopify product links so users can visit the merchant's Shopify storefront",
        "Maintain app connection status",
        "Provide support, security, and troubleshooting",
        "Comply with Shopify platform requirements and applicable privacy obligations",
        "Allow approved Brand Admins to configure reward offers that users can claim with SQRATCH points",
        "Generate single-use Shopify discount codes when eligible SQRATCH users redeem reward offers",
        "Restrict discount codes to selected Shopify products or all eligible products, depending on the Brand Admin's reward configuration",
        "Check discount code status and usage information for reward history and troubleshooting",
      ],
    },
    {
      title: "4. Shopify Access Tokens",
      paragraphs: [
        "When a merchant connects Shopify to SQRATCH, Shopify provides an access token that allows SQRATCH to access the Shopify permissions approved by the merchant during installation.",
        "SQRATCH stores this token in encrypted form. The token is used to fetch product information, create single-use reward discount codes, and read discount-code status for the connected Shopify store.",
        "If the merchant disconnects Shopify from SQRATCH or uninstalls the app from Shopify, SQRATCH clears the stored token and marks the Shopify connection as disconnected or uninstalled.",
      ],
    },
    {
      title: "5. Product and Discount Data",
      paragraphs: [
        "SQRATCH may store or display Shopify product information such as product names, images, prices, variants, handles, and public product URLs. This product data is used to help brands display Shopify products inside SQRATCH experiences, lessons, and product discovery areas.",
        "SQRATCH may also create and store information about Shopify discount codes generated through SQRATCH rewards, including the generated code, discount amount, applicable products, usage limits, expiration date, Shopify discount identifiers, and redemption status.",
        "Product purchases are completed on the merchant's Shopify store. SQRATCH does not process Shopify payments, orders, fulfillment, returns, taxes, shipping, or checkout transactions.",
      ],
    },
    {
      title: "6. Account Approval and Brand Access",
      paragraphs: [
        "SQRATCH is built for approved brand partners. Merchants may need approval before accessing the full SQRATCH platform.",
        "If a user applies for Brand access, SQRATCH may collect information needed to review and approve the Brand account.",
      ],
    },
    {
      title: "7. Data Sharing",
      paragraphs: [
        "SQRATCH does not sell personal data.",
        "SQRATCH may share limited information with trusted service providers that help operate the platform, such as hosting providers, database providers, authentication services, analytics tools, and email providers. These providers are used only to support the operation, security, and delivery of SQRATCH services.",
        "SQRATCH may also disclose information if required by law, legal process, or to protect the rights, security, and integrity of SQRATCH, merchants, users, or the public.",
      ],
    },
    {
      title: "8. Data Retention",
      paragraphs: [
        "SQRATCH retains Shopify connection data, product-related data, reward offer records, discount-code records, and redemption records for as long as needed to provide the service, support connected Brand accounts, comply with legal obligations, resolve disputes, prevent abuse, troubleshoot issues, and maintain platform security.",
        "When a merchant uninstalls the Shopify app, SQRATCH clears the stored Shopify access token and marks the store connection as uninstalled. Some non-sensitive records, such as connection history, product links, reward offer history, and redemption records, may be retained where necessary for audit, troubleshooting, abuse prevention, legal compliance, or platform continuity. Existing discount codes already created in Shopify may remain in the merchant's Shopify Admin unless the merchant disables or deletes them in Shopify.",
      ],
    },
    {
      title: "9. Shopify Privacy Webhooks",
      paragraphs: [
        "SQRATCH responds to Shopify's required privacy and compliance webhooks, including:",
      ],
      bullets: [
        "Customer data request",
        "Customer data redaction",
        "Shop data redaction",
        "Because SQRATCH does not request Shopify customer data, most customer data requests will not involve Shopify customer records stored by SQRATCH. If SQRATCH receives a valid privacy request from Shopify, SQRATCH will process it according to Shopify requirements and applicable law.",
      ],
    },
    {
      title: "10. Security",
      paragraphs: [
        "SQRATCH uses reasonable administrative, technical, and organizational safeguards to protect data. These safeguards include encrypted token storage, access controls, authentication, and secure infrastructure practices.",
        "No system is completely secure, and SQRATCH cannot guarantee absolute security.",
      ],
    },
    {
      title: "11. Merchant Controls",
      paragraphs: [
        "Merchants can disconnect Shopify from the SQRATCH dashboard. Merchants can also uninstall the SQRATCH app from Shopify Admin.",
        "Disconnecting or uninstalling the app prevents SQRATCH from continuing to use the Shopify access token to fetch product data, create new Shopify discount codes, or check Shopify discount-code status. Existing discount codes already created in Shopify may remain in the merchant's Shopify Admin unless the merchant disables or deletes them in Shopify.",
      ],
    },
    {
      title: "12. Children's Privacy",
      paragraphs: [
        "SQRATCH is not intended for children under 13. SQRATCH does not knowingly collect personal information from children under 13.",
      ],
    },
    {
      title: "13. International Users",
      paragraphs: [
        "SQRATCH may process information in the United States or other locations where our service providers operate. By using SQRATCH, users understand that information may be processed outside their country of residence.",
      ],
    },
    {
      title: "14. Changes to This Policy",
      paragraphs: [
        "SQRATCH may update this Privacy Policy from time to time. If we make material changes, we will update the effective date and may notify users through the platform or by email.",
      ],
    },
    {
      title: "15. Contact Us",
      paragraphs: [
        "For privacy questions or data requests, contact us at:",
        "support@sqratch.com",
        "Sqratch Inc.",
        "280 Albert Street, Suite 706,",
        "Ottawa ON K1P 5P3",
      ],
    },
  ],
};
